name: belief
channels:
  - anaconda
  - huggingface
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10.16
  - cudatoolkit=11.8
  - pytorch=2.1.0
  - torchvision=0.16.0
  - matplotlib=3.10.0
  - numpy=2.1.2
  - jupyter=1.0.0
  - ipykernel=6.25.0
  - pip=23.0.1
  - tqdm=4.65.0
  - pip:
      - annotated-types==0.7.0
      - nnsight==0.4.3
      - einops==0.8.1
      - fire==0.5.0
      - sentencepiece==0.1.97
      - transformers==4.48.3
      - datasets==2.11.0
      - tokenizers==0.21.0
      - dataclasses-json==0.6.7
      - huggingface-hub==0.28.1